name: spliceai
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2023.11.17=hf0a4a13_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.44.2=h091b4b1_0
  - libzlib=1.2.13=h53f4e23_5
  - ncurses=6.4=h463b476_2
  - openssl=3.2.0=h0d3ecfb_1
  - pip=23.3.2=pyhd8ed1ab_0
  - python=3.11.0=h3ba56d0_1_cpython
  - readline=8.2=h92ec313_1
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - dm-tree==0.1.8
      - flatbuffers==23.5.26
      - gast==0.5.4
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - h5py==3.10.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - keras==2.15.0
      - libclang==16.0.6
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.4
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - namex==0.0.7
      - numpy==1.26.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.2.0
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyfaidx==0.8.1.1
      - pygments==2.17.2
      - pysam==0.22.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rsa==4.9
      - six==1.16.0
      - spliceai==1.3.1
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.15.0
      - termcolor==2.4.0
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - zipp==3.17.0
prefix: /Users/ekaterinashitik/miniforge3/envs/spliceai
name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2023.11.17=h8857fd0_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.44.2=h091b4b1_0
  - libzlib=1.2.13=h53f4e23_5
  - ncurses=6.4=h463b476_2
  - openssl=3.2.0=hd75f5a5_1
  - pip=23.3.2=pyhd8ed1ab_0
  - python=3.11.0=h3ba56d0_1_cpython
  - python_abi=3.11=4_cp311
  - pyvcf=0.6.8=py311h6eed73b_1003
  - readline=8.2=h92ec313_1
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
      - argcomplete==3.2.1
      - argh==0.31.1
      - biopython==1.83
      - filelock==3.13.1
      - fsspec==2023.12.2
      - gffutils==0.12
      - importlib-metadata==7.0.1
      - jinja2==3.1.3
      - markupsafe==2.1.4
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - pandas==2.2.0
      - pangolin==1.0.2
      - pyfaidx==0.8.1.1
      - pyfastx==2.0.2
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - simplejson==3.19.2
      - six==1.16.0
      - sympy==1.12
      - torch==2.1.2
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - zipp==3.17.0
prefix: /Users/ekaterinashitik/miniforge3/envs/pangolin
name: cis_use
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2023.11.17=hf0a4a13_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.44.2=h091b4b1_0
  - libzlib=1.2.13=h53f4e23_5
  - ncurses=6.4=h463b476_2
  - openssl=3.2.0=h0d3ecfb_1
  - pip=23.3.2=pyhd8ed1ab_0
  - python=3.8.18=h2469fbe_1_cpython
  - readline=8.2=h92ec313_1
  - setuptools=69.0.3=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - cispliceai==1.1.1
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth==2.27.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - h5py==3.10.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - keras==2.13.1
      - libclang==16.0.6
      - markdown==3.5.2
      - markupsafe==2.1.4
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.0.3
      - protobuf==4.25.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyfaidx==0.8.1.1
      - pysam==0.22.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - six==1.16.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-macos==2.13.0
      - termcolor==2.4.0
      - typing-extensions==4.5.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - zipp==3.17.0
prefix: /Users/ekaterinashitik/miniforge3/envs/cis_use
name: ird_project
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2024.2.2=hf0a4a13_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.45.3=h091b4b1_0
  - libzlib=1.2.13=h53f4e23_5
  - ncurses=6.4.20240210=h078ce10_0
  - openssl=3.3.0=h0d3ecfb_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.11.0=h3ba56d0_1_cpython
  - readline=8.2=h92ec313_1
  - setuptools=69.5.1=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h57fd34a_0
  - pip:
      - anyio==4.3.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fonttools==4.51.0
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - ipykernel==6.29.4
      - ipython==8.24.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.1
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tornado==6.4
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
prefix: /Users/ekaterinashitik/miniforge3/envs/ird_project
